name: Build

# Control when the action will run
on:
  # Triggers the workflow on push events
  push:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Check-out repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Check out code
        uses: actions/checkout@v4

      - name: Yarn Install and Cache
        uses: graasp/graasp-deploy/.github/actions/yarn-install-and-cache@v1
        with:
          cypress: false

      # type check
      - name: Type-check code
        run: tsc --noEmit

      - name: Build App
        run: yarn build
        shell: bash
        env:
          VITE_PORT: 3112
          VITE_VERSION: build-ci
          VITE_GRAASP_DOMAIN: localhost
          VITE_GRAASP_API_HOST: http://localhost:3636
          VITE_GRAASP_AUTH_HOST: http://localhost:3001
          VITE_GRAASP_BUILDER_HOST: http://localhost:3111
          VITE_SHOW_NOTIFICATIONS: true
