name: cypress tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Yarn install and cache
        uses: graasp/graasp-deploy/.github/actions/yarn-install-and-cache@v1
        with:
          cypress: true

      - name: cypress run
        uses: cypress-io/github-action@v4
        env:
          REACT_APP_API_HOST: ${{ secrets.REACT_APP_API_HOST }}
          REACT_APP_GRAASP_COMPOSE_HOST: http://localhost:3111
          REACT_APP_AUTHENTICATION_HOST: http://localhost:3001
          REACT_APP_NODE_ENV: test
          REACT_APP_DOMAIN: 'localhost'
          # mock values
          REACT_APP_HIDDEN_ITEM_TAG_ID: 12345678-1234-1234-1234-123456789012
        with:
          install: false
          config: baseUrl=http://localhost:3000
          start: yarn start:ci
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 180
          browser: chrome
          quiet: true

      - name: coverage report
        run: npx nyc report --reporter=text-summary
